/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Signup */
        post: operations["signup_api_v1_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_v1_projects__project_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/spec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Video Spec
         * @description VideoSpec を取得する。なければ 404。
         */
        get: operations["get_video_spec_api_v1_projects__project_id__spec_get"];
        /**
         * Upsert Video Spec
         * @description VideoSpec を upsert する（既存あれば更新、なければ作成）。
         */
        put: operations["upsert_video_spec_api_v1_projects__project_id__spec_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/spec-draft/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Spec Draft
         * @description 自然言語入力から AI による SpecDraft 生成をバックグラウンドで開始する。結果は GET /spec-draft でポーリングする。
         */
        post: operations["generate_spec_draft_api_v1_projects__project_id__spec_draft_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/spec-draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Spec Draft
         * @description 最新の SpecDraft を取得する（version 降順で最初の1件）。なければ 404。
         */
        get: operations["get_spec_draft_api_v1_projects__project_id__spec_draft_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/spec-draft/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Spec Draft
         * @description 最新 SpecDraft を承認し、その内容で VideoSpec を作成/更新する。
         */
        post: operations["approve_spec_draft_api_v1_projects__project_id__spec_draft_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/structure/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Structure
         * @description AI による Structure 生成をバックグラウンドで開始する。結果は GET /structure でポーリングする。
         */
        post: operations["generate_structure_api_v1_projects__project_id__structure_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/structure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Structure
         * @description 最新の Structure を取得する（version 降順で最初の1件）。なければ 404。
         */
        get: operations["get_structure_api_v1_projects__project_id__structure_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/structure/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Structure
         * @description 最新 Structure を承認し、プロジェクト status を 'storyboard' に更新する。
         *
         *     3案(options)が存在する場合は option_index で選んだ案をトップレベルの
         *     scenes/rationale/total_duration_sec に反映する。省略時は 0（デフォルトプレビュー
         *     として生成完了時に既にミラーされている案）が選ばれるため、既存の無パラメータ呼び出しと
         *     完全に後方互換になる。
         */
        post: operations["approve_structure_api_v1_projects__project_id__structure_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/structure/revise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revise Structure
         * @description 承認済みの最新 Structure に対する修正指示から、改訂版（1件）の生成をバックグラウンドで開始する。
         *
         *     元の3案のうち承認された1案の内容のみを元に改訂する。結果は GET /structure でポーリングする。
         */
        post: operations["revise_structure_api_v1_projects__project_id__structure_revise_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/storyboard/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Storyboard
         * @description 承認済みの Structure から絵コンテ生成をバックグラウンドで開始する。結果は GET /storyboard でポーリングする。
         */
        post: operations["generate_storyboard_api_v1_projects__project_id__storyboard_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/storyboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Storyboard
         * @description 最新の Storyboard を取得する（version 降順で最初の1件）。なければ 404。
         */
        get: operations["get_storyboard_api_v1_projects__project_id__storyboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/storyboard/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Storyboard
         * @description 最新 Storyboard を承認し、プロジェクト status を 'shooting' に更新する。
         */
        post: operations["approve_storyboard_api_v1_projects__project_id__storyboard_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/storyboard/revise": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revise Storyboard
         * @description 承認済みの最新 Storyboard に対する修正指示から、改訂版の生成をバックグラウンドで開始する。
         *
         *     結果は GET /storyboard でポーリングする。
         */
        post: operations["revise_storyboard_api_v1_projects__project_id__storyboard_revise_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/shooting-list/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Shooting List
         * @description 承認済みの Storyboard から撮影リスト生成をバックグラウンドで開始する。結果は GET /shooting-list でポーリングする。
         */
        post: operations["generate_shooting_list_api_v1_projects__project_id__shooting_list_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/shooting-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Shooting List
         * @description 最新の ShootingList を取得する（version 降順で最初の1件）。なければ 404。
         */
        get: operations["get_shooting_list_api_v1_projects__project_id__shooting_list_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/shooting-list/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Shooting List Csv
         * @description 最新 ShootingList を CSV（UTF-8 BOM付き）でダウンロードする。
         */
        get: operations["export_shooting_list_csv_api_v1_projects__project_id__shooting_list_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/shooting-list/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Shooting List
         * @description 最新 ShootingList を承認し、プロジェクト status を 'upload' に更新する。
         */
        post: operations["approve_shooting_list_api_v1_projects__project_id__shooting_list_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/shooting-list/shots/{cut_number}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Toggle Shooting List Shot
         * @description 最新 ShootingList の指定 cut_number の撮影完了フラグを更新する。
         */
        patch: operations["toggle_shooting_list_shot_api_v1_projects__project_id__shooting_list_shots__cut_number__patch"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/shooting-list/shots/{cut_number}/generate-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Shot Image
         * @description 撮影リストの1ショットから絵コンテイラストをバックグラウンドで生成する（202）。
         *
         *     結果は GET .../shots/{cut_number}/image-status でポーリングする。承認は不要で、
         *     生成完了後は即座に画像を利用できる。既存のショットに対する再実行は上書き生成する。
         */
        post: operations["generate_shot_image_api_v1_projects__project_id__shooting_list_shots__cut_number__generate_image_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/shooting-list/shots/{cut_number}/image-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Shot Image Status
         * @description 指定ショットの絵コンテイラスト生成状況を取得する（ポーリング用）。未生成なら404。
         */
        get: operations["get_shot_image_status_api_v1_projects__project_id__shooting_list_shots__cut_number__image_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/shooting-list/shots/{cut_number}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Shot Image
         * @description 生成済み絵コンテイラスト画像をバイナリで配信する（認証必須）。
         */
        get: operations["get_shot_image_api_v1_projects__project_id__shooting_list_shots__cut_number__image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/music-analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Music Analysis
         * @description 保存済みの音楽解析結果を取得する（再アップロード不要）。なければ404。
         */
        get: operations["get_music_analysis_api_v1_projects__project_id__music_analysis_get"];
        put?: never;
        /**
         * Analyze Music
         * @description アップロードされた音声ファイル（mp3/wav）をessentiaで解析し、結果をDBに保存して返す。
         *
         *     プロジェクトごとに1件（再アップロードで上書き）。
         */
        post: operations["analyze_music_api_v1_projects__project_id__music_analysis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Characters
         * @description プロジェクトのキャラクター一覧を表示順（sort_order）で返す。
         */
        get: operations["list_characters_api_v1_projects__project_id__characters_get"];
        put?: never;
        /**
         * Create Character
         * @description キャラクターを作成する（name + prompt）。prompt はFLUXにそのまま渡す全文テキスト。
         *
         *     sort_order は既存キャラクターの最大値+1（末尾に追加）とする。
         */
        post: operations["create_character_api_v1_projects__project_id__characters_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/characters/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Reorder Characters
         * @description character_ids の並び順（indexそのまま）を sort_order として保存する。
         */
        patch: operations["reorder_characters_api_v1_projects__project_id__characters_reorder_patch"];
        trace?: never;
    };
    "/api/v1/projects/{project_id}/characters/export-zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Characters Zip
         * @description 承認済みキャラクターのモデルシート画像を sort_order 順にZIPへまとめてダウンロードする。
         *
         *     承認済みが0件の場合は404。画像ファイルが見つからないキャラクターはスキップする。
         */
        get: operations["export_characters_zip_api_v1_projects__project_id__characters_export_zip_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/characters/{character_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Character */
        get: operations["get_character_api_v1_characters__character_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Character
         * @description キャラクターを削除する（承認済みでも削除可）。モデルシート画像があればファイルも削除する。
         */
        delete: operations["delete_character_api_v1_characters__character_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Character
         * @description キャラクター名を変更する。nameのみ更新し、他のフィールドは変更しない。
         */
        patch: operations["update_character_api_v1_characters__character_id__patch"];
        trace?: never;
    };
    "/api/v1/characters/{character_id}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Character Sheet
         * @description モデルシート生成をバックグラウンドで開始する。結果は GET /characters/{id} でポーリングする。
         *
         *     承認済みキャラクターは再生成不可。生成中の再実行は409。それ以外（draft/generated/failed）は
         *     generate の再実行で上書き生成する。
         */
        post: operations["generate_character_sheet_api_v1_characters__character_id__generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/characters/{character_id}/sheet-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Character Sheet Image
         * @description 生成済みモデルシート画像をバイナリで配信する（認証必須）。
         */
        get: operations["get_character_sheet_image_api_v1_characters__character_id__sheet_image_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/characters/{character_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Character
         * @description 生成済みモデルシートを承認する。承認後は再生成できなくなる。
         */
        post: operations["approve_character_api_v1_characters__character_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_analyze_music_api_v1_projects__project_id__music_analysis_post */
        Body_analyze_music_api_v1_projects__project_id__music_analysis_post: {
            /**
             * File
             * Format: binary
             */
            file: string;
        };
        /** CharacterCreateRequest */
        CharacterCreateRequest: {
            /** Name */
            name: string;
            /** Prompt */
            prompt: string;
        };
        /** CharacterReorderRequest */
        CharacterReorderRequest: {
            /** Character Ids */
            character_ids: string[];
        };
        /** CharacterResponse */
        CharacterResponse: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Name */
            name: string;
            /** Prompt */
            prompt: string;
            /** Sheet Image Path */
            sheet_image_path: string | null;
            status: components["schemas"]["CharacterStatus"];
            /** Error Message */
            error_message: string | null;
            /** Sort Order */
            sort_order: number;
            /** Approved At */
            approved_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * CharacterStatus
         * @enum {string}
         */
        CharacterStatus: "draft" | "generating" | "generated" | "failed" | "approved";
        /** CharacterUpdateRequest */
        CharacterUpdateRequest: {
            /** Name */
            name: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MusicAnalysisResponse */
        MusicAnalysisResponse: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Filename */
            filename: string;
            /** Bpm */
            bpm: number;
            /** Key */
            key: string;
            /** Scale */
            scale: string;
            /** Key Strength */
            key_strength: number;
            /**
             * Analyzed At
             * Format: date-time
             */
            analyzed_at: string;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Title */
            title: string;
            video_type: components["schemas"]["VideoType"];
        };
        /** ProjectResponse */
        ProjectResponse: {
            /** Id */
            id: string;
            /** User Id */
            user_id: string;
            /** Organization Id */
            organization_id: string | null;
            /** Title */
            title: string;
            video_type: components["schemas"]["VideoType"];
            status: components["schemas"]["ProjectStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ProjectStatus
         * @enum {string}
         */
        ProjectStatus: "setup" | "music" | "structure" | "storyboard" | "shooting" | "upload" | "export";
        /** SceneItem */
        SceneItem: {
            /** Number */
            number: number;
            /** Title */
            title: string;
            /** Duration Sec */
            duration_sec: number;
            /** Description */
            description: string;
            /** Shot Type */
            shot_type: string;
            /** Mood */
            mood: string;
            /** Notes */
            notes: string;
        };
        /** ShootingListResponse */
        ShootingListResponse: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Storyboard Id */
            storyboard_id: string;
            /** Shots */
            shots: components["schemas"]["ShootingListShot"][];
            /** Version */
            version: number;
            status: components["schemas"]["ShootingListStatus"];
            /** Error Message */
            error_message: string | null;
            /** Approved At */
            approved_at: string | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /**
         * ShootingListShot
         * @description 永続化・レスポンス形（AI生成フィールド + バックエンド計算のcut_number/completed）。
         */
        ShootingListShot: {
            /** Cut Number */
            cut_number: number;
            /** Scene Number */
            scene_number: number;
            /**
             * Category
             * @enum {string}
             */
            category: "exterior" | "people" | "product" | "broll" | "other";
            /** Title */
            title: string;
            /** Location */
            location: string;
            /** Equipment */
            equipment: string;
            /** Talent Props */
            talent_props: string;
            /** Notes */
            notes: string;
            /** Completed */
            completed: boolean;
        };
        /** ShootingListShotToggleRequest */
        ShootingListShotToggleRequest: {
            /** Completed */
            completed: boolean;
        };
        /**
         * ShootingListStatus
         * @enum {string}
         */
        ShootingListStatus: "pending" | "completed" | "failed";
        /** ShotImageGenerateRequest */
        ShotImageGenerateRequest: {
            /**
             * Style
             * @default
             */
            style: string;
        };
        /** ShotImageResponse */
        ShotImageResponse: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Shooting List Id */
            shooting_list_id: string;
            /** Cut Number */
            cut_number: number;
            /** Image Path */
            image_path: string | null;
            status: components["schemas"]["ShotImageStatus"];
            /** Error Message */
            error_message: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ShotImageStatus
         * @enum {string}
         */
        ShotImageStatus: "generating" | "generated" | "failed";
        /** SignupRequest */
        SignupRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Name */
            name: string;
        };
        /** SpecDraftGenerateRequest */
        SpecDraftGenerateRequest: {
            /** Raw Input */
            raw_input: string;
        };
        /** SpecDraftResponse */
        SpecDraftResponse: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Raw Input */
            raw_input: string;
            /** Duration Sec */
            duration_sec: number;
            /** Target Audience */
            target_audience: string;
            /** Message */
            message: string;
            /** Mood */
            mood: string;
            /** Style Notes */
            style_notes: string | null;
            /** Reference Urls */
            reference_urls: string[];
            /** Rationale */
            rationale: string;
            /** Version */
            version: number;
            status: components["schemas"]["SpecDraftStatus"];
            /** Error Message */
            error_message: string | null;
            /** Approved At */
            approved_at: string | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /**
         * SpecDraftStatus
         * @enum {string}
         */
        SpecDraftStatus: "pending" | "completed" | "failed";
        /** StoryboardResponse */
        StoryboardResponse: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Structure Id */
            structure_id: string;
            /** Scenes */
            scenes: components["schemas"]["StoryboardScene"][];
            /** Version */
            version: number;
            status: components["schemas"]["StoryboardStatus"];
            /** Error Message */
            error_message: string | null;
            /** Human Feedback */
            human_feedback: string | null;
            /** Based On Storyboard Id */
            based_on_storyboard_id: string | null;
            /** Approved At */
            approved_at: string | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /** StoryboardReviseRequest */
        StoryboardReviseRequest: {
            /** Feedback */
            feedback: string;
        };
        /**
         * StoryboardScene
         * @description 永続化・レスポンス形（AI生成フィールド + バックエンド計算のtime_start/time_end）。
         */
        StoryboardScene: {
            /** Scene Number */
            scene_number: number;
            /** Time Start */
            time_start: number;
            /** Time End */
            time_end: number;
            /** Intent */
            intent: string;
            /** Composition */
            composition: string;
            /** Camera Work */
            camera_work: string;
            /** Text Overlay */
            text_overlay: string;
        };
        /**
         * StoryboardStatus
         * @enum {string}
         */
        StoryboardStatus: "pending" | "completed" | "failed";
        /** StructureOption */
        StructureOption: {
            /** Scenes */
            scenes: components["schemas"]["SceneItem"][];
            /** Rationale */
            rationale: string;
            /** Total Duration Sec */
            total_duration_sec: number;
        };
        /** StructureResponse */
        StructureResponse: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Scenes */
            scenes: components["schemas"]["SceneItem"][];
            /** Rationale */
            rationale: string;
            /** Total Duration Sec */
            total_duration_sec: number;
            /** Options */
            options: components["schemas"]["StructureOption"][];
            /** Version */
            version: number;
            status: components["schemas"]["StructureStatus"];
            /** Error Message */
            error_message: string | null;
            /** Selected Option Index */
            selected_option_index: number | null;
            /** Human Feedback */
            human_feedback: string | null;
            /** Based On Structure Id */
            based_on_structure_id: string | null;
            /** Approved At */
            approved_at: string | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
        };
        /** StructureReviseRequest */
        StructureReviseRequest: {
            /** Feedback */
            feedback: string;
        };
        /**
         * StructureStatus
         * @enum {string}
         */
        StructureStatus: "pending" | "completed" | "failed";
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserResponse"];
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Name */
            name: string;
            /** Organization Id */
            organization_id: string | null;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VideoSpecCreate */
        VideoSpecCreate: {
            /** Duration Sec */
            duration_sec: number;
            /** Target Audience */
            target_audience: string;
            /** Message */
            message: string;
            /** Mood */
            mood: string;
            /** Style Notes */
            style_notes?: string | null;
            /** Reference Urls */
            reference_urls?: string[];
        };
        /** VideoSpecResponse */
        VideoSpecResponse: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Duration Sec */
            duration_sec: number;
            /** Target Audience */
            target_audience: string;
            /** Message */
            message: string;
            /** Mood */
            mood: string;
            /** Style Notes */
            style_notes: string | null;
            /** Reference Urls */
            reference_urls: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * VideoType
         * @enum {string}
         */
        VideoType: "brand" | "corporate" | "recruitment" | "sns_ad" | "youtube" | "short" | "product_pr";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    signup_api_v1_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"][];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_v1_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_video_spec_api_v1_projects__project_id__spec_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoSpecResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_video_spec_api_v1_projects__project_id__spec_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VideoSpecCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoSpecResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_spec_draft_api_v1_projects__project_id__spec_draft_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpecDraftGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecDraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_spec_draft_api_v1_projects__project_id__spec_draft_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpecDraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_spec_draft_api_v1_projects__project_id__spec_draft_approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoSpecResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_structure_api_v1_projects__project_id__structure_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_structure_api_v1_projects__project_id__structure_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_structure_api_v1_projects__project_id__structure_approve_post: {
        parameters: {
            query?: {
                option_index?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revise_structure_api_v1_projects__project_id__structure_revise_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StructureReviseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StructureResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_storyboard_api_v1_projects__project_id__storyboard_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_storyboard_api_v1_projects__project_id__storyboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_storyboard_api_v1_projects__project_id__storyboard_approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revise_storyboard_api_v1_projects__project_id__storyboard_revise_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoryboardReviseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoryboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_shooting_list_api_v1_projects__project_id__shooting_list_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShootingListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shooting_list_api_v1_projects__project_id__shooting_list_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShootingListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_shooting_list_csv_api_v1_projects__project_id__shooting_list_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_shooting_list_api_v1_projects__project_id__shooting_list_approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShootingListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_shooting_list_shot_api_v1_projects__project_id__shooting_list_shots__cut_number__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                cut_number: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShootingListShotToggleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShootingListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_shot_image_api_v1_projects__project_id__shooting_list_shots__cut_number__generate_image_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                cut_number: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShotImageGenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShotImageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shot_image_status_api_v1_projects__project_id__shooting_list_shots__cut_number__image_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                cut_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShotImageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_shot_image_api_v1_projects__project_id__shooting_list_shots__cut_number__image_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                cut_number: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_music_analysis_api_v1_projects__project_id__music_analysis_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MusicAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_music_api_v1_projects__project_id__music_analysis_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_music_api_v1_projects__project_id__music_analysis_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MusicAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_characters_api_v1_projects__project_id__characters_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_character_api_v1_projects__project_id__characters_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reorder_characters_api_v1_projects__project_id__characters_reorder_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterReorderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_characters_zip_api_v1_projects__project_id__characters_export_zip_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_character_api_v1_characters__character_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_character_api_v1_characters__character_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_character_api_v1_characters__character_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CharacterUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_character_sheet_api_v1_characters__character_id__generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_character_sheet_image_api_v1_characters__character_id__sheet_image_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_character_api_v1_characters__character_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
